config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  match 'calculate_bmi', to: 'home#calculate_bmi', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  scope :get_category, ->(bmi) { where("? >= start and ? <= end_at", bmi, bmi) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def calculate_bmi
    redirect_to root_path and return if params[:user].nil?
    begin
      @bmi = params[:user][:weight].to_f / params[:user][:height].to_f ** 2
      @category = Category.get_category(@bmi).first
      current_user.update_attributes(bmi: @bmi, category_id: @category.id)
    rescue
      flash[:message] = "Invalid data"
    end

    render :index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h2 class='page-header'>Calculate BMI</h1>

<div class="row">
  <div class="col-md-4">
    <% if flash.now[:message].present? %>
      <div class="alert alert-danger" role="danger">
        <%= flash.now[:message] %>
      </div>
    <% end %>

    <%= form_tag(calculate_bmi_path, {class: 'form-horizontal'}) do %>
      <div class="form-group">
        <label for="weight" class="control-label col-sm-2">
          Weight
        </label>
        <div class="col-sm-10">
          <%= number_field :user, :weight, step: :any, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <label for="height" class="control-label col-sm-2">
          Height
        </label>
        <div class="col-sm-10">
          <%= number_field :user, :height, step: :any, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Calculate</button>
        </div>
      </div>
    <% end %>
  </div>

  <div class="col-md-6">
    <% if  @bmi.present? and @category.present? %>
      <div class="alert alert-info" role="alert">
        Your BMI is:
        <strong><%= @bmi.to_f.round(2) %></strong> .
        Considered: <strong><%= @category.description %></strong>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Body Mass Index Calculator</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BMI Calculator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class='container'>
      <h2>Body Mass Index</h2>
      <p>This is a Ruby on Rails web application that allow users to calculate Body Mass Index in order to know overweight or underweight.</p>

      <%= yield %>
    </div>
  </body>
</html>